const config = {
	tabwidth: 4,
	softtabs: true,
	linebreaks: true,

	syncurl: true,
	msgtimeout: 1200,
	autosave: 'md.doc',

	split: 'v',

	greeting: [
		'# md',
		'',
		'A markdown editor. No frameworks, no CDN, no build step.',
		'Four files, zero dependencies.',
		'',
		'## keys',
		'',
		'| key      | action        |',
		'|----------|---------------|',
		'| C-b      | bold          |',
		'| C-i      | italic        |',
		'| C-e      | code          |',
		'| C-k      | link          |',
		'| C-1..3   | heading       |',
		'| C-.      | quote         |',
		'| C-8      | list          |',
		'| C-Enter  | code block    |',
		'| C-s      | copy share url|',
		'| C-p      | toggle preview|',
		'| C-Space  | toggle split  |',
		'',
		'> The document lives in the URL. Copy it, that is the sharing.',
		'',
		'```c',
		'/* everything else is a feature request */',
		'int main(void) { return 0; }',
		'```',
	].join('\n'),
};

const keys = [
	[1, 'b',      'wrap',   ['**', '**']],
	[1, 'i',      'wrap',   ['*', '*']],
	[1, 'e',      'wrap',   ['`', '`']],
	[1, 'd',      'wrap',   ['~~', '~~']],
	[1, 'k',      'link',   null],
	[1, '1',      'prefix', '# '],
	[1, '2',      'prefix', '## '],
	[1, '3',      'prefix', '### '],
	[1, '.',      'prefix', '> '],
	[1, '8',      'prefix', '- '],
	[1, '7',      'prefix', '1. '],
	[1, '-',      'prefix', '---\n'],
	[1, 'Enter',  'wrap',   ['```\n', '\n```']],
	[1, 's',      'share',  null],
	[1, 'p',      'zoom',   null],
	[1, ' ',      'split',  null],
	[1, 'l',      'clear',  null],
];
