const config = {
	tabwidth: 4,
	softtabs: true,
	linebreaks: true,

	syncurl: true,
	msgtimeout: 1200,
	autosave: 'md.doc',

	split: 'v',

	/* toolbar layout: keys from the table below, | is a separator, '' hides it */
	toolbar: 'b i d e | 1 2 3 | . 8 7 | k - Enter',

	greeting: [
		'# md',
		'',
		'A markdown editor. No frameworks, no CDN, no build step.',
		'Four files, zero dependencies.',
		'',
		'## keys',
		'',
		'| key      | action        |',
		'|----------|---------------|',
		'| C-b      | bold          |',
		'| C-i      | italic        |',
		'| C-e      | code          |',
		'| C-k      | link          |',
		'| C-1..3   | heading       |',
		'| C-.      | quote         |',
		'| C-8      | list          |',
		'| C-Enter  | code block    |',
		'| C-s      | copy share url|',
		'| C-p      | toggle preview|',
		'| C-Space  | toggle split  |',
		'',
		'> The document lives in the URL. Copy it, that is the sharing.',
		'',
		'```c',
		'/* everything else is a feature request */',
		'int main(void) { return 0; }',
		'```',
	].join('\n'),
};

/* ctrl, key, command, argument, toolbar label */
const keys = [
	[1, 'b',      'wrap',   ['**', '**'],       'bold'],
	[1, 'i',      'wrap',   ['*', '*'],         'italic'],
	[1, 'e',      'wrap',   ['`', '`'],         'code'],
	[1, 'd',      'wrap',   ['~~', '~~'],       'strike'],
	[1, 'k',      'link',   null,               'link'],
	[1, '1',      'prefix', '# ',               'h1'],
	[1, '2',      'prefix', '## ',              'h2'],
	[1, '3',      'prefix', '### ',             'h3'],
	[1, '.',      'prefix', '> ',               'quote'],
	[1, '8',      'prefix', '- ',               'list'],
	[1, '7',      'prefix', '1. ',              'ol'],
	[1, '-',      'prefix', '---\n',            'hr'],
	[1, 'Enter',  'wrap',   ['```\n', '\n```'], 'block'],
	[1, 's',      'share',  null,               'share'],
	[1, 'p',      'zoom',   null,               'preview'],
	[1, ' ',      'split',  null,               'split'],
	[1, 'l',      'clear',  null,               'clear'],
];
